[package]
name = "alicorn_r"
authors = ["skjsjhb"]
version = "0.1.0"
edition = "2024"

[[bin]]
name = "alicorn"
path = "src/main.rs"

[workspace]
members = ["crates/alicorn-napi", "crates/alicorn-build"]
# Don't make block consider itself being in a workspace
exclude = ["patches/block"]
default-members = ["."]
resolver = "3"

[lints]
workspace = true

[workspace.lints.clippy]
allow_attributes_without_reason = "warn"
arithmetic_side_effects = "warn"
as_pointer_underscore = "warn"
assigning_clones = "warn"
borrow_as_ptr = "warn"
branches_sharing_code = "warn"
cfg_not_test = "warn"
checked_conversions = "warn"
clone_on_ref_ptr = "warn"
collection_is_never_read = "warn"
dbg_macro = "warn"
derive_partial_eq_without_eq = "warn"
doc_broken_link = "warn"
doc_comment_double_space_linebreaks = "warn"
elidable_lifetime_names = "warn"
equatable_if_let = "warn"
error_impl_error = "warn"
exit = "warn"
explicit_into_iter_loop = "warn"
explicit_iter_loop = "warn"
field_scoped_visibility_modifiers = "warn"
flat_map_option = "warn"
float_cmp = "warn"
float_cmp_const = "warn"
format_collect = "warn"
inconsistent_struct_constructor = "warn"
items_after_statements = "warn"
iter_filter_is_ok = "warn"
iter_filter_is_some = "warn"
linkedlist = "warn"
manual_assert = "warn"
manual_assert_eq = "warn"
manual_instant_elapsed = "warn"
manual_is_variant_and = "warn"
manual_let_else = "warn"
mismatching_type_param_order = "warn"
missing_const_for_fn = "warn"
mod_module_files = "warn"
needless_collect = "warn"
needless_continue = "warn"
needless_for_each = "warn"
needless_type_cast = "warn"
option_option = "warn"
or_fun_call = "warn"
redundant_closure_for_method_calls = "warn"
redundant_pub_crate = "warn"
ref_binding_to_reference = "warn"
ref_option = "warn"
same_name_method = "warn"
search_is_some = "warn"
semicolon_inside_block = "warn"
semicolon_if_nothing_returned = "warn"
semicolon_outside_block = "warn"
similar_names = "warn"
suboptimal_flops = "warn"
todo = "warn"
too_long_first_doc_paragraph = "warn"
too_many_lines = "warn"
unchecked_time_subtraction = "warn"
unicode_not_nfc = "warn"
unwrap_used = "warn"
uninlined_format_args = "warn"
unnecessary_box_returns = "warn"
unnecessary_debug_formatting = "warn"
unnecessary_semicolon = "warn"
unnecessary_trailing_comma = "warn"
unnested_or_patterns = "warn"
use_self = "warn"
used_underscore_binding = "warn"
used_underscore_items = "warn"
useless_let_if_seq = "warn"
wildcard_dependencies = "warn"

[features]
prefer-rust-impl = []

[dependencies]
lzma-rust2 = "0.21.0"
thiserror = "2.0"
tempfile = "3.27"
delegate = "0.13.5"
static-dispatch = "0.3.0"
faster-hex = "1.0.0"
digest = "0.11.3"
derive_more = { version = "2.1", features = ["from"] }
sha1 = "0.11.0"
sha2 = "0.11.0"
serde = { version = "1.0", features = ["derive"] }
serde-evolve = "0.1.0"
serde_json = "1.0"
serde_with = "3.24"
smol = "2.0.2"
regex-lite = "0.1.9"
url = "2.5"
urlencoding = "2.1"
sanitise-file-name = "1.0"
md-5 = "0.11.0"
quick-xml = { version = "0.42.0", features = ["serialize"] }
typed-path = "0.12.3"
iced = { version = "0.14.0", default-features = false, features = ["x11", "wayland", "smol", "wgpu"] }

[target.'cfg(target_vendor = "apple")'.dependencies]
common-crypto = "0.3.0"

[target.'cfg(target_os = "windows")'.dependencies]
windows = { version = "0.62.2", default-features = false, features = ["Win32_Security_Cryptography"] }
flate2 = { version = "1.1", default-features = false, features = ["zlib-rs", "runtime_detection"] }

[target.'cfg(any(target_os = "macos", target_os = "linux"))'.dependencies]
flate2 = { version = "1.1", default-features = false, features = ["zlib"] }

[build-dependencies]
alicorn-build = { path = "crates/alicorn-build" }
cfg_aliases = "0.2.2"
pkg-config = "0.3.33"
toml = "1.1"

[patch.crates-io]
block = { path = "patches/block" } # Fix a soundness issue

[profile.release]
codegen-units = 1
opt-level = "s"
lto = "fat"
strip = "symbols"

[profile.dev.package."*"]
opt-level = 2

[profile.test.package."*"]
opt-level = 0 # Makes CI faster

[profile.release.package]
iced_wgpu = { opt-level = 3 }
wgpu = { opt-level = 3 }
wgpu-core = { opt-level = 3 }
wgpu-hal = { opt-level = 3 }
cryoglyph = { opt-level = 3 }
iced_graphics = { opt-level = 3 }
cosmic-text = { opt-level = 3 }
harfrust = { opt-level = 3 }
swash = { opt-level = 3 }
skrifa = { opt-level = 3 }
read-fonts = { opt-level = 3 }
zeno = { opt-level = 3 }
yazi = { opt-level = 3 }
lzma-rust2 = { opt-level = 3 }
tiny-skia = { opt-level = 3 }
tiny-skia-path = { opt-level = 3 }
iced_tiny_skia = { opt-level = 3 }
sha1 = { opt-level = 3 }
sha2 = { opt-level = 3 }
md-5 = { opt-level = 3 }
iced_core = { opt-level = 3 }
iced_widget = { opt-level = 3 }
naga = { opt-level = 3 }
zlib-rs = { opt-level = 3 }
