[package]
name = "alicorn_r"
authors = ["skjsjhb"]
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[lints.clippy]
allow_attributes_without_reason = "warn"
arithmetic_side_effects = "warn"
as_pointer_underscore = "warn"
assigning_clones = "warn"
borrow_as_ptr = "warn"
branches_sharing_code = "warn"
cfg_not_test = "warn"
checked_conversions = "warn"
clone_on_ref_ptr = "warn"
collection_is_never_read = "warn"
dbg_macro = "warn"
derive_partial_eq_without_eq = "warn"
doc_broken_link = "warn"
doc_comment_double_space_linebreaks = "warn"
elidable_lifetime_names = "warn"
equatable_if_let = "warn"
error_impl_error = "warn"
exit = "warn"
explicit_into_iter_loop = "warn"
explicit_iter_loop = "warn"
field_scoped_visibility_modifiers = "warn"
flat_map_option = "warn"
float_cmp = "warn"
float_cmp_const = "warn"
format_collect = "warn"
inconsistent_struct_constructor = "warn"
items_after_statements = "warn"
iter_filter_is_ok = "warn"
iter_filter_is_some = "warn"
linkedlist = "warn"
manual_assert = "warn"
manual_assert_eq = "warn"
manual_instant_elapsed = "warn"
manual_is_variant_and = "warn"
manual_let_else = "warn"
mismatching_type_param_order = "warn"
missing_const_for_fn = "warn"
mod_module_files = "warn"
needless_collect = "warn"
needless_continue = "warn"
needless_for_each = "warn"
needless_type_cast = "warn"
option_option = "warn"
or_fun_call = "warn"
redundant_closure_for_method_calls = "warn"
redundant_pub_crate = "warn"
ref_binding_to_reference = "warn"
ref_option = "warn"
same_name_method = "warn"
search_is_some = "warn"
semicolon_inside_block = "warn"
semicolon_if_nothing_returned = "warn"
semicolon_outside_block = "warn"
similar_names = "warn"
suboptimal_flops = "warn"
todo = "warn"
too_long_first_doc_paragraph = "warn"
too_many_lines = "warn"
unchecked_time_subtraction = "warn"
unicode_not_nfc = "warn"
unwrap_used = "warn"
uninlined_format_args = "warn"
unnecessary_box_returns = "warn"
unnecessary_debug_formatting = "warn"
unnecessary_semicolon = "warn"
unnecessary_trailing_comma = "warn"
unnested_or_patterns = "warn"
use_self = "warn"
used_underscore_binding = "warn"
used_underscore_items = "warn"
useless_let_if_seq = "warn"
wildcard_dependencies = "warn"

[features]
prefer-rust-impl = []

[dependencies]
napi = { version = "3.13", features = ["napi10"] }
napi-derive = "3.6"
lzma-rust2 = "0.21.0"
thiserror = "2.0"
rayon = "1.12"
tempfile = "3.27"
delegate = "0.13.5"
static-dispatch = "0.3.0"
faster-hex = "1.0.0"
digest = "0.11.3"
sha1 = "0.11.0"
sha2 = "0.11.0"

[target.'cfg(target_vendor = "apple")'.dependencies]
common-crypto = "0.3.0"

[target.'cfg(target_os = "windows")'.dependencies]
windows = { version = "0.62.2", default-features = false, features = ["Win32_Security_Cryptography"] }

[build-dependencies]
napi-build = "2.5"
cfg_aliases = "0.2.2"

[profile.release]
lto = true
strip = "symbols"
