use std::collections::BTreeMap;
use std::io::Write;
use std::path::Path;
use std::path::PathBuf;

use flate2::Compression;
use flate2::write::ZlibEncoder;
use rayon::prelude::*;
use serde::Deserialize;

/// Build tasks keyed by their generated Rust module names.
#[derive(Debug, Default, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct BuildConfig {
    /// Files to embed, processed in module-name order.
    #[serde(default)]
    pub embed: BTreeMap<String, EmbedConfig>,
}

/// An input file and its embedding format.
#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct EmbedConfig {
    /// Input path, resolved relative to the project root.
    pub path: PathBuf,
    /// Format of the embedded content.
    #[serde(rename = "type")]
    pub kind: EmbedType,
}

/// Supported embedded content formats.
#[derive(Debug, Copy, Clone, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum EmbedType {
    /// Store the compressed file data.
    Data,
}

/// Main build logic.
pub fn build(config: &BuildConfig, root: &Path, output: &Path) {
    let output = output.join("embed");
    std::fs::create_dir_all(&output).expect("The embedded output directory should be writable");

    config
        .embed
        .par_iter()
        .for_each(|(name, entry)| make_embed(name, entry, root, &output));
}

fn make_embed(name: &str, entry: &EmbedConfig, root: &Path, output: &Path) {
    let EmbedType::Data = entry.kind;
    let input = root.join(&entry.path);
    println!("cargo:rerun-if-changed={}", input.display());
    let bytes = std::fs::read(&input)
        .unwrap_or_else(|ex| panic!("Can't read input file at {}: {ex}", input.display()));

    let mut encoder = ZlibEncoder::new(Vec::new(), Compression::best());
    encoder
        .write_all(&bytes)
        .expect("Embedded data should compress");
    let compressed = encoder
        .finish()
        .expect("Embedded compression should finish");

    let data_filename = format!("{name}.dat");
    let len = bytes.len();

    let source = format!(
        r#"// This file is @generated by alicorn-build.
#[allow(unused, reason = "Generated code")]
mod {name} {{
    use crate::kit::storage::embed::EmbeddedData;
    use std::sync::Arc;
    use std::sync::LazyLock;

    /// Embedded file data.
    ///
    /// Note: This value is a constant, meaning that it's copied at each call site. Use
    /// [`LAZY_DATA`] for a unique lazily-initialized value.
    pub const DATA: EmbeddedData<'static> = EmbeddedData::new(
        include_bytes!({data_filename:?}),
        {len},
    );

    /// Lazily-initialized value of [`DATA`] stored in an [`Arc`].
    pub static LAZY_DATA: LazyLock<Arc<[u8]>> = LazyLock::new(|| DATA.decode().into());
}}
"#
    );

    for (file, content) in [
        (data_filename, compressed.as_slice()),
        (format!("{name}.rs"), source.as_bytes()),
    ] {
        let path = output.join(file);
        std::fs::write(&path, content)
            .unwrap_or_else(|ex| panic!("Can't write output file at {}: {ex}", path.display()));
    }
}
