name: TypeScript CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  type-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v6
        with:
          node-version-file: .node-version

      - name: Install Linux Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --yes pkg-config zlib1g-dev
      - name: Install Rust Toolchain
        run: rustup show
      - uses: Swatinem/rust-cache@v2
      - uses: taiki-e/install-action@just

      - name: Install Dependencies
        run: npm ci
      - name: Check Types
        run: npm run type-check
